#include <iostream>
#include <memory>
#include "Vtb_fifo.h"
#include "verilated.h"
#include "verilated_vcd_c.h"

int main(int argc, char** argv) {
    // Create Verilator context
    const std::unique_ptr<VerilatedContext> contextp{new VerilatedContext};
    contextp->commandArgs(argc, argv);

    // Instantiate the top module (Vtb_fifo.h is generated by Verilator)
    const std::unique_ptr<Vtb_fifo> top{new Vtb_fifo{contextp.get()}};

    // Waveform Setup
    Verilated::traceEverOn(true);
    VerilatedVcdC* tfp = new VerilatedVcdC;
    top->trace(tfp, 99);
    tfp->open("fifo_waveform.vcd");

    // Initialize clock to 0 so the first edge is a rising edge
    top->clk = 0;

    // Simulation Loop
    // This runs until the SystemVerilog code calls $finish
    while (!contextp->gotFinish()) {
        contextp->timeInc(5);        // Advance time 5ns
        top->clk = !top->clk;        // Toggle clock (10ns period / 100MHz)
        top->eval();                 // Evaluate the model
        tfp->dump(contextp->time()); // Write to VCD file
    }

    // Cleanup and Close
    tfp->close();
    std::cout << "--- Simulation Finished ---" << std::endl;
    std::cout << "Waveform saved to: fifo_waveform.vcd" << std::endl;

    return 0;
}