# --- Variables ---
VERILATOR = verilator
RTL_DIR = rtl
DV_DIR = dv
TOP_MODULE = tb_top

# --- Build Rules ---
all: compile run


compile:
	@echo "--- STEP 1: Verilating (Translating SV to C++) ---"
	$(VERILATOR) -Wall --trace --timing --cc \
		-I$(RTL_DIR) \
		$(DV_DIR)/$(TOP_MODULE).sv \
		--top-module $(TOP_MODULE) \
		--exe $(DV_DIR)/sim_main.cpp

	@echo "--- STEP 2: Building the Executable ---"
	# This compiles the C++ code generated by Verilator into a binary
	make -C obj_dir -f V$(TOP_MODULE).mk V$(TOP_MODULE)

run:
	@echo "--- STEP 3: Running Simulation ---"
	# Execute the simulation binary
	./obj_dir/V$(TOP_MODULE)

# --- Cleanup ---
clean:
	@echo "Cleaning up project files..."
	rm -rf obj_dir waveform.vcd